.PHONY: prepare

prepare:
	mkdir -p static/assets
	cp -r node_modules/govuk-frontend/dist/govuk/assets/images/* static/assets/images
	cp -r node_modules/govuk-frontend/dist/govuk/assets/fonts/* static/assets/fonts
	cp -r node_modules/govuk-frontend/dist/govuk/assets/rebrand/* static/assets/rebrand
	cp node_modules/govuk-frontend/dist/govuk/assets/manifest.json static/assets/manifest.json
