tables:
  - name: "dept_contacts"
    source_file: "mock_rag_data.csv"
    primary_key: "id"
    columns:
      uid: "TEXT"
      service_name: "TEXT"
      department: "TEXT"
      tags: "TEXT"
      description: "TEXT"
      phone_number: "TEXT"
      embedding: "VECTOR(1024)"
    embedding_source_cols: # Define which columns should be combined to create the embedding
      [
        "department",
        "service_name",
        "topic",
        "tags",
        "description",
        "user_type",
      ]

  - name: "interaction_memory"
    source_file: "interaction_memory.csv"
    columns:
      intent_type: "TEXT"
      user_query_pattern: "TEXT"
      verified_response: "TEXT"
      handling_strategy: "TEXT"
      # No embedding column here means this table stays as plain text

  - name: "dept_contacts_v3"
    source_file: "mock_rag_data_v3.csv"
    primary_key: "id"
    columns:
      uid: "TEXT"
      service_name: "TEXT"
      department: "TEXT"
      tags: "TEXT"
      description: "TEXT"
      phone_number: "TEXT"
      live_chat_identifier: "TEXT"
      knowledge_base_identifier: "TEXT"
      embedding: "VECTOR(1024)"
    embedding_source_cols:
      [
        "department",
        "service_name",
        "topic",
        "tags",
        "description",
        "user_type",
      ]

  - name: "knowledge_bases"
    primary_key: "id"
    columns:
      external_id: "TEXT UNIQUE"
      title: "TEXT"
      content: "TEXT"
      kb_identifier: "TEXT"
      external_url: "TEXT"
      embedding: "VECTOR(1024)"
    embedding_source_cols:
      [
        "title",
        "content"
      ]

  - name: "sync_kb_metadata"
    columns:
      kb_identifier: "TEXT PRIMARY KEY"
      last_modified: "TEXT"
