import pytest
import httpx
from unittest.mock import patch, AsyncMock, MagicMock

from app.agentcore.orchestrator.tools import (
    VPCETransport,
    query_department_database,
    crm_live_chat_tools
)

# =====================================================================
# 1. VPC TRANSPORT TESTS
# =====================================================================

@pytest.mark.asyncio
async def test_vpce_transport_rewrites_host_and_url():
    """
    Test that the custom transport overrides the physical URL host to hit the VPCE,
    but retains the Canonical Host in the headers for AWS SigV4 validation.
    """
    transport = VPCETransport(vpce_host="vpce.mock.aws", canonical_host="canonical.mock.aws")

    # Simulate outgoing request generated by MCP SDK
    request = httpx.Request("POST", "https://canonical.mock.aws/mcp")

    # Patch underlying httpx transport handler so it doesn't fire onto the network
    with patch("httpx.AsyncHTTPTransport.handle_async_request", new_callable=AsyncMock) as mock_super:
        mock_super.return_value = httpx.Response(200)
        await transport.handle_async_request(request)

    # Assert 1: Header was explicitly set to the canonical host
    assert request.headers.get("Host") == "canonical.mock.aws"

    # Assert 2: Actual routing URL was swapped to the VPCE host
    assert request.url.host == "vpce.mock.aws"


# =====================================================================
# 2. RUNNABLE CONFIG EXTRACTION TESTS
# =====================================================================

@pytest.mark.asyncio
@patch("app.agentcore.orchestrator.tools.ClientSession")
@patch("app.agentcore.orchestrator.tools.aws_iam_streamablehttp_client")
async def test_crm_live_chat_tools_extracts_config(mock_stream_client, mock_client_session):
    """
    Test that the CRM tool successfully parses the RunnableConfig injected by LangGraph
    and forwards thread_id and actor_id to the MCP Gateway.
    """
    # 1. Setup nested Async Context Manager Mocks
    mock_session_instance = AsyncMock()
    mock_session_instance.call_tool.return_value = MagicMock(
        isError=False,
        content=[MagicMock(text="Live chat available")]
    )

    # Mock: async with ClientSession() as session:
    mock_client_session.return_value.__aenter__.return_value = mock_session_instance

    # Mock: async with aws_iam_streamablehttp_client() as (read, write, _):
    mock_stream_cm = AsyncMock()
    mock_stream_cm.__aenter__.return_value = (AsyncMock(), AsyncMock(), AsyncMock())
    mock_stream_client.return_value = mock_stream_cm

    # 2. Define the inputs
    tool_args = {
        "method": "check_chat_availability",
        "live_chat_identifier": "hmrc-taxes",
        "reason": "Complex question",
        "summary": "User needs help with tax bracket."
    }

    mock_config = {
        "configurable": {
            "thread_id": "thread-abc-123",
            "actor_id": "actor-xyz-987"
        }
    }

    # 3. Invoke the LangChain tool directly
    result = await crm_live_chat_tools.ainvoke(tool_args, config=mock_config)

    # 4. Assertions
    assert result == "Live chat available"

    mock_session_instance.call_tool.assert_called_once()
    call_args = mock_session_instance.call_tool.call_args

    tool_name = call_args[0][0]
    mcp_arguments = call_args[1]["arguments"]

    assert tool_name == "unit-crm-availability___check_chat_availability"
    assert mcp_arguments["thread_id"] == "thread-abc-123"
    assert mcp_arguments["actor_id"] == "actor-xyz-987"
    assert mcp_arguments["method"] == "check_chat_availability"


# =====================================================================
# 3. ERROR HANDLING TESTS
# =====================================================================

@pytest.mark.asyncio
@patch("app.agentcore.orchestrator.tools.ClientSession")
@patch("app.agentcore.orchestrator.tools.aws_iam_streamablehttp_client")
async def test_tool_handles_mcp_gateway_error(mock_stream_client, mock_client_session):
    """
    Test that if the MCP SDK throws an unhandled exception (e.g. network timeout),
    the tool safely catches it and returns a string error to the LLM rather than crashing.
    """
    mock_session_instance = AsyncMock()
    mock_session_instance.call_tool.side_effect = Exception("Connection timed out")

    mock_client_session.return_value.__aenter__.return_value = mock_session_instance

    mock_stream_cm = AsyncMock()
    mock_stream_cm.__aenter__.return_value = (AsyncMock(), AsyncMock(), AsyncMock())
    mock_stream_client.return_value = mock_stream_cm

    # Dummy config since query_department_database doesn't explicitly read it
    result = await query_department_database.ainvoke({"query": "passports"}, config={"configurable": {}})

    assert result == "ERROR: Gateway call failed: Connection timed out"
