name: App Unit Tests

on:
  pull_request:
    branches:
      - main

  # for testing - remove once confirmed working
  push:
    branches:
      - automate-unit-tests

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: app
        run: uv sync --frozen

      - name: Run unit tests
        working-directory: app
        run: uv run pytest
